version: '3.3'
services:
  db:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE_NAME}
    ports:
      - ${PORT_DATABASE_LOCAL}:${PORT_DATABASE_CONTAINER}
  api:
    build: .
    container_name: nest-bp
    image: nest-bp
    env_file:
      - .env
    ports:
      - ${PORT_LOCAL}:${PORT_CONTAINER}
    environment:
      - DATABASE_URL=${DATABASE_URL_CONTAINER}
    depends_on:
      - db
    links:
      - db
    volumes:
      - './:/src/'
volumes:
  db:
    driver: local
    